baseURL = "http://ryuchen.github.io"
title = "Sweet House"
copyright = "Copyright © 2018–2020, WangOO and Ryuchen; all rights reserved."
languageCode = "zh_CN"
DefaultContentLanguage = "zh_CN"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = "ryuchen"
enableEmoji = true
theme = "hugo-theme-chunky-poster"
paginate = 6

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "博文"
    url = "/post/"
    weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "项目"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    identifier = "snippet"
    name = "代码"
    url = "/snippet/"
    weight = 4
  [[menu.main]]
    identifier = "essay"
    name = "随笔"
    url = "/essay/"
    weight = 5
  [[menu.main]]
    identifier = "gallery"
    name = "照片墙"
    url = "/gallery/"
    weight = 6
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 0


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params]
  author = [
    "Ryuchen",
    "WangOO"
  ]
  mainSections = "post"
  github = "https://github.com/Ryuchen"
  description = "Everyday is a holiday"
  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ["shortcodes.css"]
  customJS = []

  [params.social]
    rss = true
    email = "chenhaom1993@hotmail.com"
    github = "https://github.com/Ryuchen"
    weibo = "https://weibo.com/u/3147247770"

  [params.donate]
    slogon = "维护不易，渴望您的资助"
    wechat = "https://github.com/Ryuchen/Panda-Sandbox/raw/master/docs/sponsor/wechat.jpg"
    alipay = "https://github.com/Ryuchen/Panda-Sandbox/raw/master/docs/sponsor/alipay.jpg"

  [params.prismJS]
    enable = true
    theme = ""

[markup]
  [markup.highlight]
    codeFences = true

