baseURL = "http://ryuchen.club"
title = "Sweet House"
copyright = "Copyright © 2018–2020, WangOO and Ryuchen; all rights reserved."
paginate = 2
languageCode = "zh_CN"
DefaultContentLanguage = "zh_CN"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "dairy"
    name = "日记"
    url = "/dairy/"
    weight = 2
  [[menu.main]]
    identifier = "board"
    name = "黑板"
    url = "/board/"
    weight = 3
  [[menu.main]]
    identifier = "authors"
    name = "我们"
    url = "/authors/"
    weight = 4
  [[menu.main]]
    identifier = "gallery"
    name = "照片墙"
    url = "/gallery/"
    weight = 5
  [[menu.main]]
    identifier = "404"
    name = "寻找"
    url = "/404/"
    weight = 6
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 0


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = [
    "Ryuchen",
    "WangOO"
  ]
  description = "Everyday is a holiday"
  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "example@example.com"
    facebook = "https://facebook.com"
    twitter = "https://twitter.com"
    linkedin = "https://linkedin.com"
    stack-overflow = "https://stackoverflow.com"
    instagram = "https://stackoverflow.com"
    github = "https://github.com"
    weibo = "https://www.weibo.com"
    medium = "https://medium.com"
    pinterest = "https://pinterest.com"
    reddit = "https://reddit.com"
    gitlab = "https://gitlab.com"
    mastodon = "https://mastodon.social"
    keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = true

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
